//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doancnpm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhimEntities1 : DbContext
    {
        public PhimEntities1()
            : base("name=PhimEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_chinhanh> tbl_chinhanh { get; set; }
        public virtual DbSet<tbl_DiemTichLuy> tbl_DiemTichLuy { get; set; }
        public virtual DbSet<tbl_hoadon> tbl_hoadon { get; set; }
        public virtual DbSet<tbl_khachhang> tbl_khachhang { get; set; }
        public virtual DbSet<tbl_lichchieu> tbl_lichchieu { get; set; }
        public virtual DbSet<tbl_lichlamviec> tbl_lichlamviec { get; set; }
        public virtual DbSet<tbl_movie> tbl_movie { get; set; }
        public virtual DbSet<tbl_ngay> tbl_ngay { get; set; }
        public virtual DbSet<tbl_nhanvien> tbl_nhanvien { get; set; }
        public virtual DbSet<tbl_ticket> tbl_ticket { get; set; }
    }
}
